### PR TITLE
Added support for setting operator fader levels and muting

### PR DESCRIPTION
**Pull request by techmatt101**

### CODE REVIEW

**Comment by techmatt101** [comment]
Still testing the change works as expected, will ready PR once confirmed fully working.

**Comment by techmatt101** [comment]
Tested using atdm-1012.

**Comment by techmatt101** [comment]
Hey, @josephdadams. Thank you for your hard work on this project. I would really appreciate it if you could take a look over this PR when you get a chance. Thanks.

**Comment by josephdadams** [comment]
Looks fine to me. Can you update @companion-module/base and /tools dependencies?

**Comment by josephdadams** [comment]
I did it. And version bumped to `v1.1.0`, tagged a release, and pushed to betas

**Pull request merged**
